[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
collect_ignore = "['setup.py']"

[project.urls]
Homepage = "https://github.com/JohannesBuchner/snowline"
Source = "https://github.com/JohannesBuchner/snowline"
Documentation = "https://johannesbuchner.github.io/snowline/"
