version: 2


jobs:
  
  build:
    
    docker:
      - image: circleci/python:3.7.0
    
    steps: 
      
      - checkout
      
      - run: sudo apt-get install python3-dev python3-mpi4py python3-numpy python3-scipy 
      - run: sudo pip3 install -r pip-requirements.txt pytest-html
      - run: mkdir -p test-reports
      
      - run: coverage3 run setup.py test
      - run: python3 setup.py install --user
      
      - run: coverage3 report --include="$PWD/*" --omit="$PWD/.eggs/*"
      - run: coverage3 html --include="$PWD/*" --omit="$PWD/.eggs/*" && mv htmlcov test-reports
      
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports    


